[package]
name = "tor-rev-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
arti-client = {version = "0.26.0", features = ["static", "onion-service-client"]}
clap = { version = "4.5.26", features = ["derive"] }
either = "1.13.0"
futures = "0.3.31"
http = "1.2.0"
httparse = "1.9.5"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "full", "net"] }
tryvial = "0.2.0"
ureq = { version = "2.12.1", features = ["http-crate", "http-interop"] }
url = "2.5.4"

[profile.release]
opt-level 		= 3
lto 			= "fat"
codegen-units 	= 1
